### ISSUE TITLE
No need of  time spend section

### ISSUE THREAD

**Issue by Meetpidev** [BamaCharanChhandogi/GitFinder#103]
Here its its no need to show this time sped as its chating web... and if someone wants to see it then they can go to his GitHub account.. 
so its no need to display it..

![image](https://github.com/user-attachments/assets/6d425490-4b35-4942-91d8-1e47790a10b9)

**Comment by Meetpidev** [comment]
@BamaCharanChhandogi Can i do this ?

**Comment by BamaCharanChhandogi** [comment]
It is a unique feature. That's why we kept this feature.
