### ISSUE TITLE
Issue in Incrementing the LIKE count of the Comments

### ISSUE THREAD

**Issue by Somyajain2004** [BamaCharanChhandogi/GitFinder#109]
https://github.com/user-attachments/assets/a7513bde-5ed5-4669-bdf7-43d3de6d7d5a

On liking a comment of any user, the prior count resets to 1.
As shown in the attached video, before i liked the comment, it had 3 LIKES, and after liking, it now has only 1 LIKE, instead of 4.
The issue wont go even after refreshing the page.

I would like to work on this issue.

**Comment by BamaCharanChhandogi** [comment]
I think we do not have this type of issue. The like and comment section is working fine.
