### ISSUE TITLE
Unability to edit comments of oneself.

### ISSUE THREAD

**Issue by Somyajain2004** [BamaCharanChhandogi/GitFinder#110]
https://github.com/user-attachments/assets/4ef2f22c-96dd-4309-bf82-4e7f5245d835

As shown in the attached video, there's an option for user to edit their own comments after posting them. 
But the EDIT button is currently non-functional as it doesn't allow to edit the comment on clicking it.

I would like to work on this issue.

**Comment by BamaCharanChhandogi** [comment]
@Somyajain2004 You can work on it.
