### ISSUE TITLE
[Feat] : Github actions for more connectivity!

### ISSUE THREAD

**Issue by Edasgh** [BamaCharanChhandogi/GitFinder#111]
I'll implement github workflows for the following things:

1. Auto comment on issue Closed and Opened
2. Auto comment on PR mergs
3. Auto comment on PR raises

Using this workflows makes your repo more interactive !

@BamaCharanChhandogi please assign me this issue
I'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label

**Comment by BamaCharanChhandogi** [comment]
👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our GitFinder team will review it shortly. Stay tuned!

**Comment by BamaCharanChhandogi** [comment]
Do not need it at this time.
