### ISSUE TITLE
Explore Section GIF Enhancement

### ISSUE THREAD

**Issue by SCR01** [BamaCharanChhandogi/GitFinder#15]
The current GIF in the Explore section can be replaced with a more animated and visually appealing one to better capture users' attention and enhance the user experience.

### Suggested Solution
Find or create a new, more dynamic and animated GIF that fits the theme of the Explore section, making the section more engaging.

![RedNoseStudio_WeatherVane2](https://github.com/user-attachments/assets/1cb1db2a-24a5-4793-a172-3246393457a5)

### Benefits
- Improve the visual aesthetics of the Explore section.
- Provide a more engaging user experience.

**Comment by MrinmayiVerma** [comment]
Can I work on This issue

**Comment by BamaCharanChhandogi** [comment]
> Can I work on This issue

Hi @MrinmayiVerma, this issue is already working, feel free to raise another issue and work on that issue.
