### ISSUE TITLE
Add Follow on "GitHub Button" in Home Section

### ISSUE THREAD

**Issue by SCR01** [BamaCharanChhandogi/GitFinder#16]
### Description
A "Follow on GitHub" button should be added to the home section to make it easier for users to follow the project’s repository and stay updated with the latest developments.

---

### Suggested Solution
Place a "Follow on GitHub" button prominently in the home section. The button should include a GitHub logo and link to the project’s GitHub profile. 

Example button text: "Follow GitFinder on GitHub."

---

### Benefits
- Increase follower engagement with the repository.
- Make it easier for users to connect with the project and receive updates.
- Enhance the accessibility and visibility of the GitHub profile directly from the homepage.

**Comment by MrinmayiVerma** [comment]
Can I work on This issue

**Comment by saura8668** [comment]
Hi @SCR01, I would like to work on this. Can you please assign me this issue?

**Comment by SCR01** [comment]
@MrinmayiVerma I can't assign you this only the project admin can do it, and you need to raise your own issue.

**Comment by BamaCharanChhandogi** [comment]
> Hi @SCR01, I would like to work on this. Can you please assign me this issue?

This issue is already working. Feel free to raise another issue.
