### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by KiranBaliga** [BamaCharanChhandogi/GitFinder#2]
I would like to add a code of conduct developed for your repository. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext Labels.

**Comment by Ankitkrjha32** [comment]
hey i would like to add an api so that you can find the details of  many thing like follower , following , bio , date of join and much more and also wants to make the website wonderful with detailed comments please assign me this prooject

**Comment by KiranBaliga** [comment]
@Ankitkrjha32 Please create a new issue. You have commented on a different independent issue.

**Comment by Ankitkrjha32** [comment]
@KiranBaliga  ok done
