### ISSUE TITLE
Add contribution.md

### ISSUE THREAD

**Issue by kartikey369-ind** [BamaCharanChhandogi/GitFinder#20]
How about adding contribution.md file which allows user to know the steps

**Comment by kartikey369-ind** [comment]
done my work https://github.com/BamaCharanChhandogi/GitFinder/pull/28

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?

**Comment by tmsagarofficial** [comment]
> I want to work on it. Can you please assign it to me?

Hey @AnujSaha0111 This issue has been addressed by @kartikey369-ind in his PR #28 .

**Comment by tmsagarofficial** [comment]
> done my work #28

Thanks for contributing. 🚀
