### ISSUE TITLE
Background Image updation, FOOTER 

### ISSUE THREAD

**Issue by thejatingupta7** [BamaCharanChhandogi/GitFinder#25]
@BamaCharanChhandogi  I want to update the background image.
Improve it with more interactive animations.
Also, by adding a footer with an about-us section and feedback

![image](https://github.com/user-attachments/assets/a1ec4cd3-bfd0-4efe-9117-0fd4e9154913)

**Comment by marceloams** [comment]
Hi, could you please assign this task to me and provide more details on the footer layout? Thanks!
