### ISSUE TITLE
Improvement: Adding Issue Templates & Pull request Template

### ISSUE THREAD

**Issue by Khushalsarode** [BamaCharanChhandogi/GitFinder#45]
- feature
- issue
- RP
- documentation

**Comment by BamaCharanChhandogi** [comment]
👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our GitFinder team will review it shortly. Stay tuned!

**Comment by Khushalsarode** [comment]
one similar issue exits: #38

**Comment by tmsagarofficial** [comment]
@Khushalsarode You want to work on this issue?

**Comment by Khushalsarode** [comment]
Sure!
Assigned me, I will do it

**Comment by BamaCharanChhandogi** [comment]
Do not need
