### ISSUE TITLE
GSSOC EXT NOTICE: Improper Labeling in the Project

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [BamaCharanChhandogi/GitFinder#47]
Dear Project Admin, [GitFinder](https://github.com/BamaCharanChhandogi/GitFinder)

It has come to our attention that your repository not applying the necessary labels to issues and merged PRs, which is affecting contributor scores on the leaderboard.

Please ensure you use the correct labels:

- gssoc-ext
- level1, level2, level3 
- hacktoberfest-accepted (only if your repository have Hacktoberfest topic in description)

*NOTE:* Level labels should not have any dashes between them. Spaces are allowed, but no dashes should be used.

Kindly review and update the labels on your issues and PRs to ensure fairness for all contributors. Failure to address this may result in your project being flagged.

Thank you,
Core Team
GSSoC '24 Extended

**Comment by BamaCharanChhandogi** [comment]
👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our GitFinder team will review it shortly. Stay tuned!

**Comment by AKSHITHA-CHILUKA** [comment]
@BamaCharanChhandogi please respond to the issue 
Community Manager this side

**Comment by AKSHITHA-CHILUKA** [comment]
few pr's when we sent the notice , now Ig you have followed the correct labels , remember to add labels to your pr's for sure or else points will not reflect check all the pr's which you have merged
