### ISSUE TITLE
Additon of All Contributors

### ISSUE THREAD

**Issue by pavitraag** [BamaCharanChhandogi/GitFinder#52]
**Issue Template**
**Description**
We can add all the contributor's photos in Readme file as a token of appreciation for their work.
<img width="646" alt="image" src="https://github.com/user-attachments/assets/97a97ad3-1841-4fe1-8e4e-afcbb251db97">

Please assign this to me under gssoc and hacktoberfest

**Comment by BamaCharanChhandogi** [comment]
👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our GitFinder team will review it shortly. Stay tuned!

**Comment by BamaCharanChhandogi** [comment]
Already added
