### ISSUE TITLE
[ BUG ] Single User can like Posts More than Once

### ISSUE THREAD

**Issue by ParasY174** [BamaCharanChhandogi/GitFinder#57]
**Description:**
- If a user likes a  post and then refresh the page he can again like that.

![bug](https://github.com/user-attachments/assets/c5e3d1c1-313a-4238-81ab-df79b3f83df2)

**Comment by BamaCharanChhandogi** [comment]
👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our GitFinder team will review it shortly. Stay tuned!
