### ISSUE TITLE
[ BUG ] User can Like single Post more than onces 

### ISSUE THREAD

**Issue by ParasY1724** [BamaCharanChhandogi/GitFinder#58]
**Description:**
- If a user likes a  post and then refresh the page he can again like that.

![bug](https://github.com/user-attachments/assets/c5e3d1c1-313a-4238-81ab-df79b3f83df2)

**Comment by BamaCharanChhandogi** [comment]
👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our GitFinder team will review it shortly. Stay tuned!

**Comment by ParasY1724** [comment]
Please assign this task to me .

**Comment by tmsagarofficial** [comment]
Hi @ParasY1724, upon inspection yeah this issue persists. Can you explain how you want to approach to fix this issue before working on it?

**Comment by tmsagarofficial** [comment]
Assigning it to you @ParasY1724

**Comment by ParasY1724** [comment]
Current Logic just adds count by 1 , so in  database we can keep track of id's (Array of Id) for which user has liked, also which can also be used to toggle like .
