### ISSUE TITLE
Proposal to Improve Colouring, Styling, and Design Consistency

### ISSUE THREAD

**Issue by SRV30** [BamaCharanChhandogi/GitFinder#67]
I would like to enhance the project's colouring, styling, and design consistency using Tailwind CSS. This includes updating the colour palette for better contrast, standardizing UI components with Tailwind's utility classes, and optimizing layouts for a more user-friendly design. These improvements will ensure a clean, cohesive look while boosting maintainability and scalability.

**Comment by BamaCharanChhandogi** [comment]
👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our GitFinder team will review it shortly. Stay tuned!

**Comment by SRV30** [comment]
@BamaCharanChhandogi please assign this work to me

**Comment by BamaCharanChhandogi** [comment]
Same type #65
