### ISSUE TITLE
To create the terms and coniditons page

### ISSUE THREAD

**Issue by Jay-1409** [BamaCharanChhandogi/GitFinder#69]
I think this website needs a terms and conditions page/popup:
Here is what i am thinking of includuing in the terms and conditions popup.

##Terms and Conditions

1. Acceptance of Terms
By accessing or using GitFinder, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you must not use our services.

2. User Account
To access certain features of GitFinder, you must authorize your GitHub account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.

3. Use of Services
GitFinder provides tools for viewing GitHub profiles, repositories, and their associated metrics (such as stars and forks). You agree to use these services in compliance with applicable laws and regulations.

You may not misuse our services by attempting to access them using a method other than the interface we provide or by interfering with the normal functioning of GitFinder.
4. User Content
You are responsible for any content you create, including blogs and messages. By submitting content to GitFinder, you grant us a non-exclusive, royalty-free, worldwide license to use, reproduce, modify, publish, and distribute such content.

5. Data Privacy
We collect and use your data in accordance with our Privacy Policy. By using GitFinder, you consent to the processing of your personal data as described in our Privacy Policy.

6. Intellectual Property
All content and features available on GitFinder, including but not limited to text, graphics, logos, and software, are the property of GitFinder or its licensors and are protected by copyright, trademark, and other intellectual property laws.

7. Termination
We reserve the right to terminate or suspend your access to GitFinder at any time, without prior notice or liability, if you violate these Terms and Conditions or engage in conduct that we believe is harmful to the site or other users.

8. Disclaimer of Warranties
GitFinder is provided on an "as-is" and "as-available" basis. We do not warrant that the services will be uninterrupted, secure, or error-free. Your use of the services is at your own risk.

9. Limitation of Liability
In no event shall GitFinder be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or use, arising out of or in connection with your use of the services.

10. Changes to Terms
We reserve the right to modify these Terms and Conditions at any time. If we make changes, we will notify you by revising the date at the top of these terms and/or by providing a notice through our services.

i would like to work under Gssoc extd 2024 and hacktoberfest 2024
Thanks!!

**Comment by BamaCharanChhandogi** [comment]
👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our GitFinder team will review it shortly. Stay tuned!

**Comment by BamaCharanChhandogi** [comment]
Do not need it as of now.
