### ISSUE TITLE
Scroll bar of your website is not looking good and not suited on your website.

### ISSUE THREAD

**Issue by VinayLodhi1712** [BamaCharanChhandogi/GitFinder#74]
![scroll bar4](https://github.com/user-attachments/assets/3816e703-9a0b-42ea-a5db-8c01cc277712)

https://github.com/user-attachments/assets/3564a09e-b213-4b81-91f3-384390276b92

**Comment by BamaCharanChhandogi** [comment]
👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our GitFinder team will review it shortly. Stay tuned!

**Comment by BamaCharanChhandogi** [comment]
Do not need. thanks.
