### ISSUE TITLE
[FEATURE] Showing the info of the person you are chatting to on the chat page 

### ISSUE THREAD

**Issue by HemantBatra873** [BamaCharanChhandogi/GitFinder#75]
**Problem**
Currently on the chat page you can not see the profile photo and name of the person you are chatting with.

---

![gitfinder](https://github.com/user-attachments/assets/095451e6-430a-4296-96b4-2843d5595daf)

---

**Proposed solution**
I will add the profile photo and name feature on the chat . And make the chat page look much better .

**Please assign this issue to me under gssoc and hacktoberfest-accepted .**

**Comment by BamaCharanChhandogi** [comment]
👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our GitFinder team will review it shortly. Stay tuned!

**Comment by BamaCharanChhandogi** [comment]
I think its duplicate issue.

**Comment by HemantBatra873** [comment]
> I think it's a duplicate issue.

Duplicate? Is someone else already working on it? I didn't see any issues mentioning this earlier.
