### ISSUE TITLE
Add Good First issue

### ISSUE THREAD

**Issue by yashksaini-coder** [BamaCharanChhandogi/GitFinder#81]
The developer hub should be the easy go to guide for new beginners dev to find new issues daily that is available for all. If they can be find new issues quickly that can be a good feature.

@BamaCharanChhandogi review this issue & assign it to me with proper `gssoc` & `hacktoberfest` labels.

**Comment by BamaCharanChhandogi** [comment]
👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our GitFinder team will review it shortly. Stay tuned!

**Comment by yashksaini-coder** [comment]
hey @BamaCharanChhandogi what do you think of this feature

**Comment by yashksaini-coder** [comment]
@BamaCharanChhandogi hi can you assign me this issue with proper labels of `gssoc` & `hacktoberfest`

**Comment by yashksaini-coder** [comment]
@BamaCharanChhandogi hey bro can I be assigned this issue

**Comment by tmsagarofficial** [comment]
@yashksaini-coder Thanks for showing interest in contributing. But your initial message needs to be a bit more clear about what is developer hub and can you elaborate a bit more on the issue itself than the solution.?

**Comment by yashksaini-coder** [comment]
Its already in your github repo desc:-
 `GitFinder is a vibrant hub for developers, offering a space to showcase projects, discover coding trends, and connect with peers worldwide. Showcase your coding prowess, explore diverse projects, engage in discussions, and stay updated on the latest in the coding community.`

Then why don't add the functionality to search for issues, if possible we can implement a search for different labels type. How does this idea sounds ? 

@tmsagarofficial

**Comment by tmsagarofficial** [comment]
I would say this would be a nice feature.
Thanks for the clarification.

What do you say ? @BamaCharanChhandogi

**Comment by yashksaini-coder** [comment]
@tmsagarofficial @BamaCharanChhandogi well can I work on this feature ?

**Comment by tmsagarofficial** [comment]
Yeah, go ahead! Sorry for the delay.
