### ISSUE TITLE
Adding cursor following animation

### ISSUE THREAD

**Issue by amanver45** [BamaCharanChhandogi/GitFinder#97]
I would like to add a cursor following animation and make it align with the website styling
Kindly assign this to me

**Comment by BamaCharanChhandogi** [comment]
👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our GitFinder team will review it shortly. Stay tuned!

**Comment by tmsagarofficial** [comment]
@amanver45 Thanks for showing interest in contributing. Can you elaborate or like a GIF of what it would look if implemented?

**Comment by amanver45** [comment]
like this @tmsagarofficial 

Uploading Recording 2024-10-28 201513.mp4…

**Comment by BamaCharanChhandogi** [comment]
Do not need.
